Repository Black-Tek/BlackTek-Server, pull requests merged in 2025-03, with the labels that each got.

#101 Small Refactor of Combat Event Handling
  src/bed.cpp
  src/condition.cpp
  src/damagemodifier.h
  src/game.cpp
  src/spells.cpp
Labels: C++

#102 Enable Configuration option for Augments' Crit animation
  config.lua.dist
  src/combat.cpp
  src/configmanager.cpp
  src/configmanager.h
  src/enums.h
Labels: Feature, C++

#95 Remove queryAdd on closingdoor.lua
  data/movements/scripts/closingdoor.lua
Labels: Help Needed

#114 Outfits.toml Closes #91
  config/outfits.toml
  src/luascript.cpp
  src/otserv.cpp
  src/outfit.cpp
  src/outfit.h
  src/player.cpp
Labels: C++, Toml
